//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debtors
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DebtorsEntities : DbContext
    {
        public DebtorsEntities()
            : base("name=DebtorsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Debtor> Debtors { get; set; }
        public DbSet<EnforcementOrder> EnforcementOrders { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Journal> Journals { get; set; }
        public DbSet<LawCourt> LawCourts { get; set; }
        public DbSet<OrganizationInfo> OrganizationInfoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TypesDebtor> TypesDebtors { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Writ> Writs { get; set; }
        public DbSet<Сlaims> Сlaims { get; set; }
    }
}
