//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debtors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debtor
    {
        public Debtor()
        {
            this.EnforcementOrders = new HashSet<EnforcementOrder>();
            this.Journals = new HashSet<Journal>();
            this.Writs = new HashSet<Writ>();
            this.Сlaims = new HashSet<Сlaims>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public decimal Debt { get; set; }
        public string NumContract { get; set; }
        public System.DateTime DateContract { get; set; }
        public byte[] ScanContract { get; set; }
        public System.DateTime StartDateDebt { get; set; }
        public string FileExtension { get; set; }
    
        public virtual TypesDebtor TypesDebtor { get; set; }
        public virtual ICollection<EnforcementOrder> EnforcementOrders { get; set; }
        public virtual ICollection<Journal> Journals { get; set; }
        public virtual ICollection<Writ> Writs { get; set; }
        public virtual ICollection<Сlaims> Сlaims { get; set; }
    }
}
