//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debtors
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesDebtor
    {
        public TypesDebtor()
        {
            this.Debtors = new HashSet<Debtor>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Debtor> Debtors { get; set; }
    }
}
